spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.7:3306/?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000 # 连接超时时间（毫秒）
    database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）默认 -1
        max-idle: 8 # 连接池中的最大空闲连接默认 8
        min-idle: 0 # 连接池中的最小空闲连接默认 0
  cache:
    redis:
      use-key-prefix: true
      key-prefix: dev
      cache-null-values: false
      time-to-live: 20s
#mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl #关闭sql日志

mqqt:
  username: admin
  password: admin # 密码
  hostUrl: tcp://123.60.188.174:1883 # tcp://ip:端口
  clientId: photonStudio-prod # 客户端id
  defaultTopic: topic # 订阅主题
  timeout: 1000 # 超时时间 （单位：秒）
  keepalive: 60 # 心跳 （单位：秒）
  enabled: false # 是否使能mqtt功能

minio:
  endpoint: http://192.168.1.7:9000
  accessKey: minioadmin
  secretKey: zsqyminioadmin
  bucketName: images

hikvi:
  host: 172.99.0.2:443
  app-key: 23841942
  app-secret: LkG5ujkm0CQ6tPR5nqUM
  streamType: 0 # 0:主码流 1:子码流 2:第三码流
  protocol: hls # 取流协议（应用层协议）  hik,rtsp,rtmp,hls,ws
  transmode: 1 # 传输协议（传输层协议） 0:UDP 1:TCP
  expand: transcode=1&streamform=rtp # 标识扩展内容 snapshot：是否是缩略图 0表示不是缩略图，1表示是缩略图
  streamform: ps # 输出码流转封装格式  ps,rtp  当protocol=rtsp时生效